- src/main/java/it/gov/pagopa/apiconfig/cache/util/mapper/ConvertCodifichePaToEncoding.java
> fix coverage exclusion

- helm/weu-it/values-it.yaml
- helm/weu-prf/values-prf.yaml
- pom.xml
> Fix it prf

- .devops/deploy-pipelines.yml
> align_helms

- .devops/deploy-pipelines.yml
- helm/Chart.yaml
- helm/run.sh
- helm/weu-dev/values-dev.yaml
- helm/weu-it/values-it.yaml
- helm/weu-prf/values-prf.yaml
- helm/weu-prod/values-prod.yaml
- helm/weu-uat/values-uat.yaml
- src/main/java/it/gov/pagopa/apiconfig/cache/controller/FdrCacheController.java
- src/main/java/it/gov/pagopa/apiconfig/cache/service/ConfigService.java
- src/main/resources/application.properties
> Kubectl install pipeline

- helm/neu-dev/values-dev.yaml
- helm/weu-dev/values-dev.yaml
- helm/weu-it/values-it.yaml
- helm/weu-prf/values-prf.yaml
- helm/weu-prod/values-prod.yaml
- helm/weu-uat/values-uat.yaml
- openapi/openapi.json
- openapi/openapi_fdrv1.json
- openapi/openapi_nodev1.json
- openapi/openapi_verifierv1.json
- pom.xml
- src/main/java/it/gov/pagopa/apiconfig/cache/controller/CacheController.java
- src/main/java/it/gov/pagopa/apiconfig/cache/controller/FdrCacheController.java
- src/main/java/it/gov/pagopa/apiconfig/cache/controller/NodeCacheController.java
- src/main/java/it/gov/pagopa/apiconfig/cache/service/ConfigService.java
- src/main/java/it/gov/pagopa/apiconfig/cache/util/Constants.java
- src/main/java/it/gov/pagopa/apiconfig/cache/util/JsonSerializer.java
- src/main/resources/application.properties
- src/test/java/it/gov/pagopa/apiconfig/cache/RedisTest.java
- src/test/java/it/gov/pagopa/apiconfig/cache/TestValueOperation.java
-save on db table "CACHE"
-aligned helm files
expected)
> feat: Nod 303 scrittura db

- pom.xml
- src/main/java/it/gov/pagopa/apiconfig/cache/service/ConfigService.java
- src/test/java/it/gov/pagopa/apiconfig/cache/NodoConfigCacheTest.java
> Starter 1.9

- .github/workflows/deploy_with_github_runner.yml
- src/main/java/it/gov/pagopa/apiconfig/cache/service/ConfigService.java
> fix length version

- .gitignore
- helm/values-dev.yaml
- helm/values-prod.yaml
- helm/values-uat.yaml
- src/main/resources/logback-spring.xml
- new jdbc string
to resolve the JDCB Connection error
expected)
> [PAGOPA-1228] new string jdbc

- helm/values-prod.yaml
- helm/values-uat.yaml
> Added affinity prod

- helm/Chart.yaml
- helm/values-dev.yaml
- helm/values-prod.yaml
- helm/values-uat.yaml
- openapi/openapi.json
- openapi/openapi_fdrv1.json
- openapi/openapi_nodev1.json
- openapi/openapi_verifierv1.json
- pom.xml
> Fix prod helm cfg

- .github/workflows/anchore.yml
- .github/workflows/code_review.yml
- Dockerfile
- helm/Chart.yaml
- helm/values-dev.yaml
- helm/values-prod.yaml
- helm/values-uat.yaml
- openapi/openapi.json
- openapi/openapi_fdrv1.json
- openapi/openapi_nodev1.json
- openapi/openapi_standinv1.json
- openapi/openapi_verifierv1.json
- pom.xml
- src/main/java/it/gov/pagopa/apiconfig/cache/controller/CacheController.java
- src/main/java/it/gov/pagopa/apiconfig/cache/controller/RefreshController.java
- src/main/java/it/gov/pagopa/apiconfig/cache/model/RefreshResponse.java
- src/main/java/it/gov/pagopa/apiconfig/cache/service/CacheEventHubService.java
- src/main/java/it/gov/pagopa/apiconfig/cache/service/ConfigService.java
- src/main/java/it/gov/pagopa/apiconfig/cache/util/Constants.java
- src/main/resources/application-local.properties
- src/main/resources/application.properties
- src/test/java/it/gov/pagopa/apiconfig/cache/NodoConfigCacheTest.java
- src/test/java/it/gov/pagopa/apiconfig/cache/OpenApiGenerationTest.java
- src/test/java/it/gov/pagopa/apiconfig/cache/RedisTest.java
- src/test/java/it/gov/pagopa/apiconfig/cache/controller/ControllerTest.java
- src/test/resources/application.properties
- src/test/resources/logback-spring.xml
> [NOD-692] Riversamento

- helm/values-dev.yaml
- helm/values-prod.yaml
- helm/values-uat.yaml
changed endpoint on refresh in cron
expected)
> Nod 574 cronjobs

- .github/workflows/deploy_with_github_runner.yml
- helm/values-uat.yaml
- infra/04_apim_api.tf
> Export API CFG Cache

- helm/Chart.yaml
- helm/values-dev.yaml
- helm/values-prod.yaml
- helm/values-uat.yaml
- openapi/openapi.json
- openapi/openapi_export.json
- openapi/openapi_fdrv1.json
- openapi/openapi_nodev1.json
- openapi/openapi_standinv1.json
- openapi/openapi_verifierv1.json
- pom.xml
> [NOD-895] Fix helm in UAT 

- helm/neu-dev/values-dev.yaml
- helm/values-dev.yaml
- helm/values-prod.yaml
- helm/values-uat.yaml
- helm/weu-it/values-it.yaml
- helm/weu-prf/values-prf.yaml
> chore: Migrazione redis multiAZ

- infra/04_apim_api.tf
- infra/04_apim_api_oracle.tf
- infra/99_locals.tf
> fix: [NOD-911] Product-api relationship

- .github/workflows/deploy_with_github_runner.yml
- helm/Chart.yaml
- helm/values-dev.yaml
- helm/values-prod.yaml
- helm/values-uat.yaml
- openapi/openapi.json
- openapi/openapi_export.json
- openapi/openapi_fdrv1.json
- openapi/openapi_nodev1.json
- openapi/openapi_standinv1.json
- openapi/openapi_verifierv1.json
- pom.xml
> Fix prod pipeline

- .github/workflows/deploy_with_github_runner.yml
> fix runner

- src/main/java/it/gov/pagopa/apiconfig/cache/model/node/v1/creditorinstitution/Station.java
- added `isPaymentOptionsEnabled `and `restEndpoint `to `Station `model
expected)
> Update station model with OdP fields

- src/main/java/it/gov/pagopa/apiconfig/cache/util/mapper/ConvertStazioniToStationDetails.java
- added `isPaymentOptionsEnabled `and `restEndpoint `to `Station `mapper
expected)
> Update station mapper with OdP fields

- .github/workflows/deploy_with_github_runner.yml
- .github/workflows/release_deploy.yml
- .identity/00_data.tf
- Dockerfile
- helm/Chart.yaml
- helm/values-dev.yaml
- helm/values-prod.yaml
- helm/values-uat.yaml
- infra/04_apim_api_oracle.tf
- infra/04_apim_api_postgres_nexi.tf
- infra/04_apim_export.tf
- openapi/openapi.json
- openapi/openapi_export.json
- openapi/openapi_fdrv1.json
- openapi/openapi_nodev1.json
- openapi/openapi_standinv1.json
- openapi/openapi_verifierv1.json
- pom.xml
> chore: [PAGOPA-2264] Charts and deploy pipeline

- helm/Chart.yaml
- helm/values-dev.yaml
- helm/values-prod.yaml
- helm/values-uat.yaml
- openapi/openapi.json
- openapi/openapi_export.json
- openapi/openapi_fdrv1.json
- openapi/openapi_nodev1.json
- openapi/openapi_standinv1.json
- openapi/openapi_verifierv1.json
- openapi/openapi_wispv1.json
- pom.xml
- src/main/java/it/gov/pagopa/apiconfig/cache/model/latest/configuration/GdeConfiguration.java
- src/main/java/it/gov/pagopa/apiconfig/cache/util/ConfigMapper.java
- src/main/java/it/gov/pagopa/apiconfig/cache/util/mapper/entitiesToLatest/ConvertGdeConfigToGdeConfiguration.java
-  added mapper to force `GDE config` fields to upper case
[PAGOPA-2705](https://pagopa.atlassian.net/browse/PAGOPA-2705)
expected)
[PAGOPA-2705]: https://pagopa.atlassian.net/browse/PAGOPA-2705?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: [PAGOPA-2705] GDE config cache

- .github/workflows/code_review.yml
- helm/values-dev.yaml
- helm/values-prod.yaml
- helm/values-uat.yaml
- src/main/resources/application.properties
- switch from `6432` to `5432` port
- add Hikari configuration
- Bump code review GHA to `v2.2`
[PIDM-467](https://pagopa.atlassian.net/browse/PIDM-467)
expected)
[PIDM-467]: https://pagopa.atlassian.net/browse/PIDM-467?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [PIDM-467] chore: Remove pgBounce

- helm/Chart.yaml
- helm/values-dev.yaml
- helm/values-prod.yaml
- helm/values-uat.yaml
- openapi/openapi.json
- openapi/openapi_export.json
- openapi/openapi_fdrv1.json
- openapi/openapi_nodev1.json
- openapi/openapi_standinv1.json
- openapi/openapi_verifierv1.json
- openapi/openapi_wispv1.json
- pom.xml
- src/main/java/it/gov/pagopa/apiconfig/cache/service/StakeholderConfigService.java
> fix: bug elaborateStandInCache

- helm/Chart.yaml
- helm/values-dev.yaml
- helm/values-prod.yaml
- helm/values-uat.yaml
- openapi/openapi.json
- openapi/openapi_export.json
- openapi/openapi_fdrv1.json
- openapi/openapi_nodev1.json
- openapi/openapi_standinv1.json
- openapi/openapi_verifierv1.json
- openapi/openapi_wispv1.json
- pom.xml
- src/main/resources/application.properties
> chore: Change hikariCP cfg

- helm/values-dev.yaml
- infra/04_apim_api_postgres_nexi.tf
> chore: disabled postgres Nexi dev

- helm/Chart.yaml
- helm/values-dev.yaml
- helm/values-prod.yaml
- helm/values-uat.yaml
- openapi/openapi.json
- openapi/openapi_export.json
- openapi/openapi_fdrv1.json
- openapi/openapi_nodev1.json
- openapi/openapi_standinv1.json
- openapi/openapi_verifierv1.json
- openapi/openapi_wispv1.json
- pom.xml
> chore: workload identity for cronjob

- helm/Chart.yaml
- helm/values-dev.yaml
- helm/values-prod.yaml
- helm/values-uat.yaml
- openapi/openapi.json
- openapi/openapi_export.json
- openapi/openapi_fdrv1.json
- openapi/openapi_nodev1.json
- openapi/openapi_standinv1.json
- openapi/openapi_verifierv1.json
- openapi/openapi_wispv1.json
- pom.xml
Align UAT with PROD configuration values.
expected)
> [PAGOPA-3110] chore(Helm): Disable cache deployments
